### ISSUE TITLE
Feature: Strategy Execution

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-server#14]
Clients should be able to start/stop strategy instances from base strategy definitions.

### TODO
* [ ] architect strategy instance isolation (security)
* [ ] create system for starting/stopping/monitoring strategies
  * [ ] track strategy performance over time

**Comment by robertkowalski** [comment]
live strategy execution will be part of the next release
